version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: notification-service
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongo
      - rabbitmq
      # - redis

volumes:
  mongo_data:
